# (Get-Counter -ListSet PhysicalDisk).PathsWithInstances
Get-Counter -counter "\PhysicalDisk(1 D: F:)\Current Disk Queue Length",
"\PhysicalDisk(1 D: F:)\% Disk Time",
"\PhysicalDisk(1 D: F:)\Avg. Disk Queue Length",
"\PhysicalDisk(1 D: F:)\% Disk Read Time",
"\PhysicalDisk(1 D: F:)\Avg. Disk Read Queue Length",
"\PhysicalDisk(1 D: F:)\% Disk Write Time",
"\PhysicalDisk(1 D: F:)\Avg. Disk Write Queue Length",
"\PhysicalDisk(1 D: F:)\Avg. Disk sec/Transfer",
"\PhysicalDisk(1 D: F:)\Avg. Disk sec/Read",
"\PhysicalDisk(1 D: F:)\Avg. Disk sec/Write",
"\PhysicalDisk(1 D: F:)\Disk Transfers/sec",
"\PhysicalDisk(1 D: F:)\Disk Reads/sec",
"\PhysicalDisk(1 D: F:)\Disk Writes/sec",
"\PhysicalDisk(1 D: F:)\Disk Bytes/sec",
"\PhysicalDisk(1 D: F:)\Disk Read Bytes/sec",
"\PhysicalDisk(1 D: F:)\Disk Write Bytes/sec",
"\PhysicalDisk(1 D: F:)\Avg. Disk Bytes/Transfer",
"\PhysicalDisk(1 D: F:)\Avg. Disk Bytes/Read",
"\PhysicalDisk(1 D: F:)\Avg. Disk Bytes/Write",
"\PhysicalDisk(1 D: F:)\% Idle Time",
"\PhysicalDisk(1 D: F:)\Split IO/Sec" -continuous